name: GitHub Metrics

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs once every day at midnight
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_limit: 6
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          committer_message: "Update metrics [skip ci]"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
